import Header from '../components/layout/Header';
import { Logo } from '../components/ui/Logo';
import Link from 'next/link';
import { ArrowRight, Brain, Milestone, BarChart3 } from 'lucide-react';

export default function Home() {
  return (
    <div className="relative min-h-screen overflow-hidden bg-background flex flex-col justify-between">
      {/* Background Decorative Gradients */}
      <div className="absolute top-[-10%] left-[-10%] w-[500px] h-[500px] rounded-full bg-primary/10 blur-[120px] pointer-events-none" />
      <div className="absolute bottom-[-10%] right-[-10%] w-[500px] h-[500px] rounded-full bg-accent/5 blur-[120px] pointer-events-none" />

      {/* Header */}
      <Header />

      {/* Main Content */}
      <main className="max-w-7xl mx-auto px-6 py-20 flex-grow flex flex-col justify-center items-center text-center relative z-10">
        
        {/* Large Centered Logo */}
        <div className="mb-8 animate-fade-in flex justify-center">
          <Logo size="lg" />
        </div>

        {/* Hero Section */}
        <div className="max-w-3xl space-y-6">
          <h1 className="text-4xl sm:text-6xl font-extrabold tracking-tight font-heading leading-tight text-foreground">
            AI-Powered Learning for{" "}
            <span className="bg-gradient-primary bg-clip-text text-transparent">
              Modern Teams
            </span>
          </h1>
          
          <p className="text-base sm:text-lg text-muted-foreground max-w-xl mx-auto leading-relaxed">
            Personalized learning paths that help your employees grow — automatically generated by AI.
          </p>

          <div className="flex flex-wrap justify-center gap-4 pt-4">
            <Link 
              href="/register" 
              className="bg-gradient-primary hover:opacity-90 text-white font-semibold px-6 py-3 rounded-lg shadow-lg shadow-primary/20 transition-all hover:translate-y-[-1px] active:translate-y-[0px] flex items-center gap-2 border-0"
            >
              Start Free Trial <ArrowRight className="h-4 w-4 shrink-0" />
            </Link>
            
            <Link 
              href="/sign-in" 
              className="border border-border bg-card hover:bg-muted text-foreground font-semibold px-6 py-3 rounded-lg transition-all"
            >
              Sign In
            </Link>
          </div>
        </div>

        {/* Feature Cards */}
        <div className="grid md:grid-cols-3 gap-6 mt-24 w-full max-w-4xl">
          <div className="bg-card border border-border rounded-xl p-6 transition-all hover:shadow-md group text-left shadow-xs glass card-hover">
            <div className="w-10 h-10 rounded-lg bg-primary/10 border border-primary/20 text-primary flex items-center justify-center mb-4 group-hover:scale-105 transition-transform">
              <Brain className="h-5 w-5" />
            </div>
            <h3 className="font-extrabold text-foreground text-base mb-2 font-heading">AI Assessment</h3>
            <p className="text-muted-foreground text-xs leading-relaxed">
              Adaptive diagnostic interviews matching employee answers to identify concrete capability profiles.
            </p>
          </div>

          <div className="bg-card border border-border rounded-xl p-6 transition-all hover:shadow-md group text-left shadow-xs glass card-hover">
            <div className="w-10 h-10 rounded-lg bg-accent/10 border border-accent/20 text-accent flex items-center justify-center mb-4 group-hover:scale-105 transition-transform">
              <Milestone className="h-5 w-5" />
            </div>
            <h3 className="font-extrabold text-foreground text-base mb-2 font-heading">Smart Paths</h3>
            <p className="text-muted-foreground text-xs leading-relaxed">
              Dynamically generated lesson paths and modules targeting specific organizational roles.
            </p>
          </div>

          <div className="bg-card border border-border rounded-xl p-6 transition-all hover:shadow-md group text-left shadow-xs glass card-hover">
            <div className="w-10 h-10 rounded-lg bg-primary/10 border border-primary/20 text-primary flex items-center justify-center mb-4 group-hover:scale-105 transition-transform">
              <BarChart3 className="h-5 w-5" />
            </div>
            <h3 className="font-extrabold text-foreground text-base mb-2 font-heading">Team Analytics</h3>
            <p className="text-muted-foreground text-xs leading-relaxed">
              Comprehensive employee monitoring dashboard tracking active modules, logs, and completion levels.
            </p>
          </div>
        </div>
      </main>

      {/* Footer */}
      <footer className="border-t border-border py-6 text-center text-xs text-muted-foreground bg-card">
        <div className="max-w-7xl mx-auto px-6 flex flex-col md:flex-row justify-between items-center gap-4">
          <span>&copy; 2026 EZ LEARN. All rights reserved.</span>
          <div className="flex gap-4">
            <a href="#" className="hover:text-foreground transition-colors">Privacy Policy</a>
            <a href="#" className="hover:text-foreground transition-colors">Terms of Service</a>
          </div>
        </div>
      </footer>
    </div>
  );
}
