import logging
from typing import List
from langchain_openai import ChatOpenAI
from langchain_core.messages import HumanMessage, SystemMessage
from app.schemas.path import GeneratedResource, GeneratedModule
from app.config import settings
import json, re

logger = logging.getLogger(__name__)

CURATOR_PROMPT = """You are a learning resource quality expert.
Given a module topic, generate 2-3 high-quality, REAL learning resources.

Rules:
- Only include resources that ACTUALLY EXIST at these URLs
- Prefer: YouTube videos, official documentation, freeCodeCamp,
  MDN, CSS-Tricks, Kent C. Dodds blog, Josh Comeau blog,
  Fireship.io, The Odin Project, roadmap.sh, refactoring.guru
- Each resource must have a real, specific URL
- For YouTube: use youtube.com/watch?v=... format
- For articles: use the actual article URL
- Validate URL format

Return ONLY a JSON array of resources:
[
  {
    "title": "exact title",
    "url": "https://...",
    "sourcePlatform": "YouTube|MDN|freeCodeCamp|etc",
    "description": "why this is valuable (1 sentence)",
    "resourceType": "VIDEO|ARTICLE|DOCUMENTATION",
    "durationMinutes": number or null,
    "qualityScore": 8.5,
    "language": "EN"
  }
]"""

class ResourceCuratorAgent:

    def __init__(self):
        self.llm = ChatOpenAI(
            model="gpt-4o",
            temperature=0.3,
            api_key=settings.OPENAI_API_KEY,
        )

    async def curate_for_module(
        self,
        module_title: str,
        module_description: str,
        domain: str,
        level: str,
        existing_resources: List,
    ) -> List[GeneratedResource]:
        """
        For MVP: return existing resources (already generated by path agent)
        Enhanced search will be added in Phase 5 (Google Search API).
        """
        # Return existing resources as-is
        # They are already validated by GeneratedPath schema
        return existing_resources

    async def validate_and_score(
        self,
        resources: List[GeneratedResource],
    ) -> List[GeneratedResource]:
        """
        Apply quality scoring heuristics to existing resources.
        """
        scored = []
        for r in resources:
            # Boost score for known quality domains
            quality_domains = [
                'youtube.com', 'mdn.io', 'developer.mozilla.org',
                'freecodecamp.org', 'css-tricks.com', 'kentcdodds.com',
                'fireship.io', 'theodinproject.com', 'roadmap.sh',
                'refactoring.guru', 'docs.', 'github.com',
            ]
            url_lower = r.url.lower()
            quality_boost = any(d in url_lower for d in quality_domains)

            r.qualityScore = min(10.0, r.qualityScore + (1.0 if quality_boost else 0.0))
            scored.append(r)

        return scored
