export const pathReadyTemplate = (data: {
  employeeName: string;
  orgName: string;
  pathTitle: string;
  milestoneCount: number;
  estimatedHours: number;
  ctaUrl: string;
  orgLogo?: string;
}) => ({
  subject: `🎓 Your Learning Path is Ready, ${data.employeeName}!`,
  html: `
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Your Learning Path is Ready</title>
</head>
<body style="margin:0;padding:0;background:#090912;font-family:
             -apple-system,BlinkMacSystemFont,'Segoe UI',sans-serif;">

  <div style="max-width:560px;margin:0 auto;padding:32px 16px;">

    <!-- Header -->
    <div style="text-align:center;margin-bottom:32px;">
      ${
        data.orgLogo
          ? `<img src="${data.orgLogo}" alt="${data.orgName}"
                style="height:40px;object-fit:contain;margin-bottom:16px;" />`
          : `<div style="font-size:24px;font-weight:700;color:#fff;
                       margin-bottom:8px;">${data.orgName}</div>`
      }
      <div style="font-size:13px;color:#6b7280;">
        Powered by LearnPath AI
      </div>
    </div>

    <!-- Main card -->
    <div style="background:#0f1220;border:1px solid #1e2438;
                border-radius:16px;padding:32px;margin-bottom:24px;">

      <!-- Celebration emoji -->
      <div style="text-align:center;font-size:56px;margin-bottom:24px;">
        🎓
      </div>

      <h1 style="color:#fff;font-size:24px;font-weight:700;
                 text-align:center;margin:0 0 12px 0;line-height:1.3;">
        Your Learning Path is Ready!
      </h1>

      <p style="color:#9ca3af;font-size:15px;text-align:center;
                margin:0 0 28px 0;line-height:1.6;">
        Hi <strong style="color:#e5e7eb;">${data.employeeName}</strong>,
        your AI-generated learning path has been built
        specifically for your skills and goals.
      </p>

      <!-- Path details card -->
      <div style="background:#161929;border:1px solid #1e2438;
                  border-radius:12px;padding:20px;margin-bottom:28px;">
        <div style="font-size:12px;color:#6366f1;font-weight:600;
                    text-transform:uppercase;letter-spacing:0.05em;
                    margin-bottom:8px;">
          YOUR PERSONALIZED PATH
        </div>
        <div style="color:#e5e7eb;font-size:18px;font-weight:600;
                    margin-bottom:16px;">
          ${data.pathTitle}
        </div>
        <div style="display:flex;gap:16px;flex-wrap:wrap;">
          <div style="flex:1;min-width:100px;">
            <div style="color:#6b7280;font-size:12px;margin-bottom:4px;">
              MILESTONES
            </div>
            <div style="color:#e5e7eb;font-size:20px;font-weight:700;">
              ${data.milestoneCount}
            </div>
          </div>
          <div style="flex:1;min-width:100px;">
            <div style="color:#6b7280;font-size:12px;margin-bottom:4px;">
              TOTAL TIME
            </div>
            <div style="color:#e5e7eb;font-size:20px;font-weight:700;">
              ~${data.estimatedHours}h
            </div>
          </div>
        </div>
      </div>

      <!-- CTA Button -->
      <div style="text-align:center;">
        <a href="${data.ctaUrl}"
           style="display:inline-block;background:linear-gradient(135deg,#6366f1,#8b5cf6);
                  color:#fff;text-decoration:none;font-size:16px;font-weight:600;
                  padding:14px 32px;border-radius:10px;
                  box-shadow:0 0 24px rgba(99,102,241,0.3);">
          Start My Learning Path →
        </a>
      </div>
    </div>

    <!-- What's next -->
    <div style="background:#0f1220;border:1px solid #1e2438;
                border-radius:12px;padding:24px;margin-bottom:24px;">
      <div style="color:#e5e7eb;font-size:15px;font-weight:600;
                  margin-bottom:16px;">
        ✨ What to expect:
      </div>
      ${[
        [
          '🎯',
          'Milestone-by-milestone learning',
          'Each milestone unlocks as you complete the previous',
        ],
        [
          '📚',
          'Curated resources',
          'Articles, videos and exercises handpicked by AI',
        ],
        [
          '✏️',
          'Hands-on exercises',
          'Apply what you learn with real-world scenarios',
        ],
      ]
        .map(
          ([icon, title, desc]) => `
        <div style="display:flex;gap:12px;margin-bottom:14px;">
          <div style="font-size:20px;flex-shrink:0;">${icon}</div>
          <div>
            <div style="color:#e5e7eb;font-size:14px;font-weight:600;
                        margin-bottom:2px;">${title}</div>
            <div style="color:#6b7280;font-size:13px;">${desc}</div>
          </div>
        </div>
      `,
        )
        .join('')}
    </div>

    <!-- Footer -->
    <div style="text-align:center;color:#4b5563;font-size:12px;">
      <p>This learning path was generated by LearnPath AI for ${data.orgName}</p>
      <p style="margin-top:8px;">
        <a href="${data.ctaUrl}" style="color:#6366f1;text-decoration:none;">
          View your path
        </a>
        &nbsp;·&nbsp;
        <a href="#" style="color:#4b5563;text-decoration:none;">
          Unsubscribe
        </a>
      </p>
    </div>
  </div>
</body>
</html>
  `,
});
